#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TASK_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
BASE="$(cd "${TASK_ROOT}/.." && pwd)"

source "${SCRIPT_DIR}/load_deploy_config.sh"
load_deploy_config

export BASE
export TASK_ROOT
export SCHEME="${SCHEME:-stage62_glm52_opt_indexshare_rdma_mtp_skipshare_gmem092_2p1d_v2_stable}"
export SOURCE_DIR="${SOURCE_DIR:-${BASE}/vllm_glm52_v2_2nd_v2}"
export RUNTIME_PATCH_SOURCE_DIR="${RUNTIME_PATCH_SOURCE_DIR:-${SOURCE_DIR}}"
export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git -C "${SOURCE_DIR}" rev-parse HEAD 2>/dev/null || echo bfd727e11b0e501bab0a4a943d92ba5ea3b2f980)}"
export MODEL_PATH="${MODEL_PATH:-/nfs/AIED/models/GLM-5.2-FP8}"
export MODEL_ID="${MODEL_ID:-GLM-5.2-FP8}"
export IMAGE_TAG="${IMAGE_TAG:-192.168.14.129:80/ae/vllm_openai_glm52:v0.19.0-v2-stable-2p1d-usagefix-20260625_114616}"
export IMAGE_TAR="${IMAGE_TAR:-${TASK_ROOT}/artifacts/images/vllm_openai_glm52_v2_stable_2p1d_usagefix_20260625_114616.tar}"
export BUILD_HOST="${BUILD_HOST:-192.168.16.77}"
export SSH_USER="${SSH_USER:-zhanghong}"
export TARGET_HOSTS="${TARGET_HOSTS:-192.168.16.63 192.168.16.65 192.168.16.68 192.168.16.69 192.168.16.76 192.168.16.77}"
export ALLOWED_HOSTS="${ALLOWED_HOSTS:-192.168.16.63,192.168.16.65,192.168.16.68,192.168.16.76,192.168.16.69,192.168.16.77}"

export PREFILL_HEAD="${PREFILL_HEAD:-192.168.16.63}"
export PREFILL_WORKER="${PREFILL_WORKER:-192.168.16.65}"
export PREFILL0_HEAD="${PREFILL0_HEAD:-192.168.16.63}"
export PREFILL0_WORKER="${PREFILL0_WORKER:-192.168.16.65}"
export PREFILL1_HEAD="${PREFILL1_HEAD:-192.168.16.68}"
export PREFILL1_WORKER="${PREFILL1_WORKER:-192.168.16.69}"
export DECODE_HEAD="${DECODE_HEAD:-192.168.16.76}"
export DECODE_WORKER="${DECODE_WORKER:-192.168.16.77}"
export PREFILL_PORT="${PREFILL_PORT:-19182}"
export DECODE_PORT="${DECODE_PORT:-19183}"
export PROXY_PORT="${PROXY_PORT:-19181}"
export PREFILL_MASTER_PORT="${PREFILL_MASTER_PORT:-32466}"
export DECODE_MASTER_PORT="${DECODE_MASTER_PORT:-32454}"
export SIDE_PORT="${SIDE_PORT:-25700}"

export NCCL_IB_HCA="${NCCL_IB_HCA:-mlx5_2,mlx5_3,mlx5_6,mlx5_7}"
export NCCL_PROTO="${NCCL_PROTO:-Simple}"
export HOST_IFACE_OVERRIDES="${HOST_IFACE_OVERRIDES:-192.168.16.68=ens22f0np0,192.168.16.69=ens22f0np0}"
export UCX_TLS="${UCX_TLS:-rc,cuda_copy,cuda_ipc}"
export UCX_DEVICES="${UCX_DEVICES:-mlx5_2:1,mlx5_3:1,mlx5_6:1,mlx5_7:1}"
export UCX_NET_DEVICES="${UCX_NET_DEVICES:-mlx5_2:1,mlx5_3:1,mlx5_6:1,mlx5_7:1}"
export UCX_MAX_RNDV_RAILS="${UCX_MAX_RNDV_RAILS:-4}"
export UCX_MAX_EAGER_RAILS="${UCX_MAX_EAGER_RAILS:-4}"
export UCX_CM_USE_ALL_DEVICES="${UCX_CM_USE_ALL_DEVICES:-y}"

export KV_BUFFER_DEVICE="${KV_BUFFER_DEVICE:-cuda}"
export NIXL_SIMPLE_EXTRA_CONFIG="${NIXL_SIMPLE_EXTRA_CONFIG:-True}"
export KV_CONNECTOR="${KV_CONNECTOR:-NixlConnector}"
export KV_LOAD_FAILURE_POLICY="${KV_LOAD_FAILURE_POLICY:-recompute}"
export ROLE_TP_SIZE="${ROLE_TP_SIZE:-2}"
export ROLE_PP_SIZE="${ROLE_PP_SIZE:-8}"
export ROLE_LAYER_PARTITION="${ROLE_LAYER_PARTITION:-10,8,8,8,12,8,12,12}"
export PREFILL_ROLE_TP_SIZE="${PREFILL_ROLE_TP_SIZE:-${ROLE_TP_SIZE}}"
export PREFILL_ROLE_PP_SIZE="${PREFILL_ROLE_PP_SIZE:-${ROLE_PP_SIZE}}"
export PREFILL_ROLE_LAYER_PARTITION="${PREFILL_ROLE_LAYER_PARTITION:-${ROLE_LAYER_PARTITION}}"
export DECODE_ROLE_TP_SIZE="${DECODE_ROLE_TP_SIZE:-${ROLE_TP_SIZE}}"
export DECODE_ROLE_PP_SIZE="${DECODE_ROLE_PP_SIZE:-${ROLE_PP_SIZE}}"
export DECODE_ROLE_LAYER_PARTITION="${DECODE_ROLE_LAYER_PARTITION:-${ROLE_LAYER_PARTITION}}"

export MAX_NUM_SEQS="${MAX_NUM_SEQS:-16}"
export PREFILL_MAX_NUM_SEQS="${PREFILL_MAX_NUM_SEQS:-16}"
export DECODE_MAX_NUM_SEQS="${DECODE_MAX_NUM_SEQS:-16}"
export VLLM_ENABLE_PREFIX_CACHING="${VLLM_ENABLE_PREFIX_CACHING:-1}"
export VLLM_ENABLE_PROMPT_TOKENS_DETAILS="${VLLM_ENABLE_PROMPT_TOKENS_DETAILS:-1}"
export MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-2048}"
export VLLM_PREFILL_SHAPE_BUCKET="${VLLM_PREFILL_SHAPE_BUCKET:-1}"
export VLLM_PREFILL_SHAPE_BUCKET_MULTIPLE="${VLLM_PREFILL_SHAPE_BUCKET_MULTIPLE:-2048}"
export VLLM_PREFILL_SHAPE_BUCKET_MAX="${VLLM_PREFILL_SHAPE_BUCKET_MAX:-2048}"
export VLLM_PREFILL_SHAPE_BUCKET_PAD_METADATA="${VLLM_PREFILL_SHAPE_BUCKET_PAD_METADATA:-1}"
export VLLM_PREFILL_SHAPE_BUCKET_PAD_ACTIVE_SEQ="${VLLM_PREFILL_SHAPE_BUCKET_PAD_ACTIVE_SEQ:-1}"
export VLLM_PREFILL_SHAPE_BUCKET_DEBUG="${VLLM_PREFILL_SHAPE_BUCKET_DEBUG:-0}"
export GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.92}"
export PREFILL_GPU_MEMORY_UTILIZATION="${PREFILL_GPU_MEMORY_UTILIZATION:-0.92}"
export DECODE_GPU_MEMORY_UTILIZATION="${DECODE_GPU_MEMORY_UTILIZATION:-0.92}"
export VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS="${VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS:-1}"
export UBATCH_SIZE="${UBATCH_SIZE:-0}"
export SERVER_SEED="${SERVER_SEED:-42}"
export STOP_NON_TASK_CONTAINERS="${STOP_NON_TASK_CONTAINERS:-1}"

export PREFILL_PROXY_MIN_DISAGG_CHARS="${PREFILL_PROXY_MIN_DISAGG_CHARS:-2048}"
export PREFILL_PROXY_LONG_PREFILL_LIMIT="${PREFILL_PROXY_LONG_PREFILL_LIMIT:-1}"
export PREFILL_PROXY_LONG_PREFILL_ROUTE_POLICY="${PREFILL_PROXY_LONG_PREFILL_ROUTE_POLICY:-least_available}"
export PREFILL_PROXY_CONTEXT_LENGTH_GUARD="${PREFILL_PROXY_CONTEXT_LENGTH_GUARD:-1}"
export PREFILL_PROXY_MAX_MODEL_LEN="${PREFILL_PROXY_MAX_MODEL_LEN:-202752}"
export VLLM_ENABLE_INDUCTOR_MAX_AUTOTUNE="${VLLM_ENABLE_INDUCTOR_MAX_AUTOTUNE:-0}"
export VLLM_ENABLE_INDUCTOR_COORDINATE_DESCENT_TUNING="${VLLM_ENABLE_INDUCTOR_COORDINATE_DESCENT_TUNING:-0}"
export VLLM_ENFORCE_EAGER="${VLLM_ENFORCE_EAGER:-0}"
export VLLM_DISABLE_CUSTOM_ALL_REDUCE="${VLLM_DISABLE_CUSTOM_ALL_REDUCE:-1}"
export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}"
export VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS="${VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS:-7200}"
export XDG_CACHE_HOME_OVERRIDE="${XDG_CACHE_HOME_OVERRIDE:-${TASK_ROOT}/cache/xdg_compilerfix3_${SCHEME}}"

_COMPILATION_CONFIG='{"mode":"VLLM_COMPILE","cudagraph_mode":"PIECEWISE","cudagraph_copy_inputs":true,"inductor_compile_config":{"combo_kernels":true,"benchmark_combo_kernel":false,"enable_auto_functionalized_v2":false,"size_asserts":false,"alignment_asserts":false,"scalar_asserts":false}}'
if [[ "${V2_DISABLE_COMPILATION_CONFIG:-0}" == "1" ]]; then
  export COMPILATION_CONFIG_JSON=""
  export COMPILATION_CONFIG_B64=""
else
  export COMPILATION_CONFIG_JSON="${COMPILATION_CONFIG_JSON:-}"
  export COMPILATION_CONFIG_B64="${COMPILATION_CONFIG_B64:-$(printf '%s' "${_COMPILATION_CONFIG}" | base64 | tr -d '\n')}"
fi

export VLLM_SPARSE_INDEXER_MQA_LOGITS_BACKEND="${VLLM_SPARSE_INDEXER_MQA_LOGITS_BACKEND:-cuda_v7}"
export VLLM_SPARSE_INDEXER_DECODE_TRIM_LOGITS="${VLLM_SPARSE_INDEXER_DECODE_TRIM_LOGITS:-1}"
export VLLM_SPARSE_INDEXER_DECODE_LOGITS_BUCKET_SIZE="${VLLM_SPARSE_INDEXER_DECODE_LOGITS_BUCKET_SIZE:-8192}"
export VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES="${VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES:-2}"
export VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES_WARPS="${VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES_WARPS:-4}"
export VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES_STAGES="${VLLM_SPARSE_INDEXER_DECODE_LOGITS_BLOCK_PAGES_STAGES:-2}"
export VLLM_SPARSE_INDEXER_DECODE_TRIM_BLOCK_TABLE="${VLLM_SPARSE_INDEXER_DECODE_TRIM_BLOCK_TABLE:-0}"
export VLLM_SPARSE_INDEXER_SKIP_DECODE_TOPK_CLEAR="${VLLM_SPARSE_INDEXER_SKIP_DECODE_TOPK_CLEAR:-1}"
export VLLM_SPARSE_INDEXER_DECODE_EMPTY_LOGITS="${VLLM_SPARSE_INDEXER_DECODE_EMPTY_LOGITS:-1}"
export VLLM_SPARSE_INDEXER_DECODE_LOGITS_WORKSPACE="${VLLM_SPARSE_INDEXER_DECODE_LOGITS_WORKSPACE:-1}"
export VLLM_SPARSE_INDEXER_DECODE_TOPK_BACKEND="${VLLM_SPARSE_INDEXER_DECODE_TOPK_BACKEND:-persistent}"
export VLLM_SPARSE_INDEXER_DECODE_FP8_LUT="${VLLM_SPARSE_INDEXER_DECODE_FP8_LUT:-1}"
export VLLM_TOPK_ENV_CACHE="${VLLM_TOPK_ENV_CACHE:-1}"

export VLLM_MQA_CUDA_V7_FUSED_TRITON="${VLLM_MQA_CUDA_V7_FUSED_TRITON:-1}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_M_MAX="${VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_M_MAX:-4}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_BLOCK_M="${VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_BLOCK_M:-1}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_BLOCK_N="${VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_BLOCK_N:-512}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_NUM_WARPS="${VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_NUM_WARPS:-4}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_NUM_STAGES="${VLLM_MQA_CUDA_V7_FUSED_TRITON_DECODE_NUM_STAGES:-3}"
export VLLM_MQA_CUDA_V7_FUSED_TRITON_PREFILL_CANONICAL_M="${VLLM_MQA_CUDA_V7_FUSED_TRITON_PREFILL_CANONICAL_M:-512}"

export VLLM_SPARSE_MLA_FORCE_KV_SPLITS="${VLLM_SPARSE_MLA_FORCE_KV_SPLITS:-1}"
export VLLM_SPARSE_MLA_FINAL_STATIC_BY_TOKENS="${VLLM_SPARSE_MLA_FINAL_STATIC_BY_TOKENS:-1}"
export VLLM_SPARSE_MLA_WARMUP_NUM_TOKENS="${VLLM_SPARSE_MLA_WARMUP_NUM_TOKENS:-2048,4096}"
export VLLM_SPARSE_MLA_DECODE_M1_FINAL64="${VLLM_SPARSE_MLA_DECODE_M1_FINAL64:-0}"
export VLLM_SPARSE_MLA_ASSUME_VALID_DYNAMIC="${VLLM_SPARSE_MLA_ASSUME_VALID_DYNAMIC:-1}"
export VLLM_SPARSE_MLA_ASSUME_VALID_NOMASK="${VLLM_SPARSE_MLA_ASSUME_VALID_NOMASK:-1}"
export VLLM_SPARSE_MLA_REQ_TO_GLOBAL_BLOCK_N="${VLLM_SPARSE_MLA_REQ_TO_GLOBAL_BLOCK_N:-256}"
export VLLM_SPARSE_MLA_FORCE_PREFIX_MASK_DECODE="${VLLM_SPARSE_MLA_FORCE_PREFIX_MASK_DECODE:-0}"
export VLLM_SPARSE_MLA_FORCE_PREFIX_MASK_DECODE_MAX_TOKENS="${VLLM_SPARSE_MLA_FORCE_PREFIX_MASK_DECODE_MAX_TOKENS:-4}"
export VLLM_SPARSE_MLA_M1_COOP_FINAL="${VLLM_SPARSE_MLA_M1_COOP_FINAL:-0}"
export VLLM_SPARSE_MLA_M1_COOP_FINAL_NUM_SPLITS="${VLLM_SPARSE_MLA_M1_COOP_FINAL_NUM_SPLITS:-32}"
export VLLM_SPARSE_MLA_M1_COOP_FINAL_LIB="${VLLM_SPARSE_MLA_M1_COOP_FINAL_LIB:-}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL:-1}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_UNSAFE_ENABLE="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_UNSAFE_ENABLE:-1}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_DECODE_ONLY="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_DECODE_ONLY:-1}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_NUM_SPLITS="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_NUM_SPLITS:-32}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_LIB="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_LIB:-/opt/glm52_speed_up_v1_stable/artifacts/native_ext/stage50_sparse_mla_m1_splitmerge_final_ops.so}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_DEBUG_LOGS="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_DEBUG_LOGS:-16}"
export VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_SYNC_DEBUG="${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_SYNC_DEBUG:-0}"

export VLLM_PP_DIRECT_RECV_INTERMEDIATE="${VLLM_PP_DIRECT_RECV_INTERMEDIATE:-1}"
export VLLM_PP_SKIP_FINAL_MAX_TOKENS_BROADCAST="${VLLM_PP_SKIP_FINAL_MAX_TOKENS_BROADCAST:-1}"
export VLLM_PP_DISABLE_INTERMEDIATE_ALLGATHER="${VLLM_PP_DISABLE_INTERMEDIATE_ALLGATHER:-1}"
export VLLM_PP_CPU_SAMPLED_TOKEN_BROADCAST="${VLLM_PP_CPU_SAMPLED_TOKEN_BROADCAST:-0}"
export VLLM_PP_CPU_FIRST_RANK_SAMPLED_TOKEN_P2P="${VLLM_PP_CPU_FIRST_RANK_SAMPLED_TOKEN_P2P:-0}"
export VLLM_PP_SAMPLED_TOKEN_RECV_BUFFER="${VLLM_PP_SAMPLED_TOKEN_RECV_BUFFER:-0}"
export VLLM_PP_SAMPLED_TOKEN_PAIR_P2P="${VLLM_PP_SAMPLED_TOKEN_PAIR_P2P:-0}"
export VLLM_PP_FIRST_RANK_ONLY_SAMPLED_TOKEN_P2P="${VLLM_PP_FIRST_RANK_ONLY_SAMPLED_TOKEN_P2P:-0}"
export VLLM_PP_ASYNC_SAMPLED_TOKEN_BROADCAST="${VLLM_PP_ASYNC_SAMPLED_TOKEN_BROADCAST:-0}"
export VLLM_PP_MIDDLE_RANK_SKIP_SAMPLED_TOKEN="${VLLM_PP_MIDDLE_RANK_SKIP_SAMPLED_TOKEN:-0}"
export VLLM_PP_BATCH_P2P_TENSOR_DICT="${VLLM_PP_BATCH_P2P_TENSOR_DICT:-0}"
export VLLM_PP_TENSOR_DICT_METADATA_CACHE="${VLLM_PP_TENSOR_DICT_METADATA_CACHE:-0}"
export VLLM_PP_DEFER_SEND_WAIT="${VLLM_PP_DEFER_SEND_WAIT:-0}"
export VLLM_PP_MAX_CONCURRENT_BATCHES="${VLLM_PP_MAX_CONCURRENT_BATCHES:-0}"
export PREFILL_VLLM_PP_MAX_CONCURRENT_BATCHES="${PREFILL_VLLM_PP_MAX_CONCURRENT_BATCHES:-0}"
export DECODE_VLLM_PP_MAX_CONCURRENT_BATCHES="${DECODE_VLLM_PP_MAX_CONCURRENT_BATCHES:-2}"
export VLLM_STAGE50_PP_READY_FIRST_DRAIN="${VLLM_STAGE50_PP_READY_FIRST_DRAIN:-0}"

export VLLM_MTP_GREEDY_ONLY="${VLLM_MTP_GREEDY_ONLY:-1}"
export VLLM_MTP_SKIP_FIRST_DRAFT="${VLLM_MTP_SKIP_FIRST_DRAFT:-1}"
export VLLM_MTP_PRESTART_ASYNC_OUTPUT_COPY="${VLLM_MTP_PRESTART_ASYNC_OUTPUT_COPY:-0}"
export VLLM_PRIORITIZE_REMOTE_KV_FIRST_DECODE="${VLLM_PRIORITIZE_REMOTE_KV_FIRST_DECODE:-0}"
export VLLM_MTP_ACCEPTANCE_LOG_EVERY="${VLLM_MTP_ACCEPTANCE_LOG_EVERY:-200}"
export VLLM_ENABLE_AUTO_TOOL_CHOICE="${VLLM_ENABLE_AUTO_TOOL_CHOICE:-1}"
export VLLM_TOOL_CALL_PARSER="${VLLM_TOOL_CALL_PARSER:-glm47}"
export VLLM_REASONING_PARSER="${VLLM_REASONING_PARSER:-glm45}"
if [[ -z "${EXTRA_SERVE_ARGS:-}" ]]; then
  export EXTRA_SERVE_ARGS='--generation-config=vllm --speculative-config={"method":"mtp","num_speculative_tokens":5,"use_local_argmax_reduction":true} --default-chat-template-kwargs={"reasoning_effort":"high","enable_thinking":true}'
else
  export EXTRA_SERVE_ARGS
fi
append_extra_serve_args_once() {
  local flag="$1"
  shift
  if [[ " ${EXTRA_SERVE_ARGS} " != *" ${flag} "* ]]; then
    EXTRA_SERVE_ARGS="${EXTRA_SERVE_ARGS} ${flag}"
    if (($# > 0)); then
      EXTRA_SERVE_ARGS="${EXTRA_SERVE_ARGS} $*"
    fi
  fi
}
append_extra_serve_args_once "--enable-force-include-usage"
case "${VLLM_ENABLE_AUTO_TOOL_CHOICE:-0}" in
  1|true|TRUE|yes|YES|on|ON)
    append_extra_serve_args_once "--enable-auto-tool-choice"
    ;;
esac
if [[ -n "${VLLM_TOOL_CALL_PARSER:-}" ]]; then
  append_extra_serve_args_once "--tool-call-parser" "${VLLM_TOOL_CALL_PARSER}"
fi
if [[ -n "${VLLM_REASONING_PARSER:-}" ]]; then
  append_extra_serve_args_once "--reasoning-parser" "${VLLM_REASONING_PARSER}"
fi
export EXTRA_SERVE_ARGS="${EXTRA_SERVE_ARGS# }"

export SSHPASS="${ZHANGHONG_PASS:-}"
if [[ -z "${SSHPASS}" ]]; then
  SSHPASS="$(awk '/passwd:/ {gsub(/`/, "", $3); if ($3 != "zh") {print $3; exit}}' "${BASE}/server_info.md")"
  export SSHPASS
  export ZHANGHONG_PASS="${SSHPASS}"
fi

SSH_OPTS=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR)

assert_allowed_host() {
  local host="$1"
  case ",${ALLOWED_HOSTS}," in
    *",${host},"*) ;;
    *)
      echo "Refusing remote operation on non-allowed host: ${host}" >&2
      return 99
      ;;
  esac
}

remote() {
  local host="$1"
  shift
  assert_allowed_host "${host}"
  sshpass -e ssh "${SSH_OPTS[@]}" "${SSH_USER}@${host}" "$@"
}

record_acceptance() {
  local stage="$1"
  local status="$2"
  local note="$3"
  mkdir -p "${TASK_ROOT}/state"
  printf '%s\t%s\t%s\t%s\n' "$(date -u +%FT%TZ)" "${stage}" "${status}" "${note}" >> "${TASK_ROOT}/state/evaluator.tsv"
}

latest_deploy_manifest() {
  local pattern="${TASK_ROOT}/reports/raw/*_deploy_manifest.json"
  ls -1t ${pattern} 2>/dev/null | head -n 1 || true
}

write_environment_md() {
  local output="${TASK_ROOT}/configs/environment.md"
  mkdir -p "${TASK_ROOT}/configs"
  cat > "${output}" <<EOF
# $(basename "${TASK_ROOT}") Environment

- source_commit: \`${SOURCE_COMMIT}\`
- source_dir: \`${SOURCE_DIR}\`
- runtime_patch_source_dir: \`${RUNTIME_PATCH_SOURCE_DIR}\`
- deploy_config_file: \`${DEPLOY_CONFIG_FILE}\`
- deploy_label: \`${DEPLOY_LABEL}\`
- scheme: \`${SCHEME}\`
- image_tag: \`${IMAGE_TAG}\`
- image_tar: \`${IMAGE_TAR}\`
- model_path: \`${MODEL_PATH}\`
- build_host: \`${BUILD_HOST}\`
- hosts: \`${TARGET_HOSTS}\`
- 1p1d_prefill: \`${PREFILL_HEAD},${PREFILL_WORKER}\`
- 1p1d_decode: \`${DECODE_HEAD},${DECODE_WORKER}\`
- 2p1d_prefill_groups: \`${PREFILL0_HEAD},${PREFILL0_WORKER};${PREFILL1_HEAD},${PREFILL1_WORKER}\`
- 2p1d_decode: \`${DECODE_HEAD},${DECODE_WORKER}\`
- ports: proxy=\`${PROXY_PORT}\`, prefill=\`${PREFILL_PORT}\`, decode=\`${DECODE_PORT}\`
- tp_pp: TP=\`${ROLE_TP_SIZE}\`, PP=\`${ROLE_PP_SIZE}\`, partition=\`${ROLE_LAYER_PARTITION}\`
- max_num_seqs: \`${MAX_NUM_SEQS}\`
- max_num_batched_tokens: \`${MAX_NUM_BATCHED_TOKENS}\`
- prefill_shape_bucket: enabled=\`${VLLM_PREFILL_SHAPE_BUCKET}\`, multiple=\`${VLLM_PREFILL_SHAPE_BUCKET_MULTIPLE}\`, max=\`${VLLM_PREFILL_SHAPE_BUCKET_MAX}\`, pad_active_seq=\`${VLLM_PREFILL_SHAPE_BUCKET_PAD_ACTIVE_SEQ}\`
- mqa_prefill_canonical_m: \`${VLLM_MQA_CUDA_V7_FUSED_TRITON_PREFILL_CANONICAL_M}\`
- kv_buffer_device: \`${KV_BUFFER_DEVICE}\`
- skip_first: \`${VLLM_MTP_SKIP_FIRST_DRAFT}\`
- fullaccept: enabled by \`${EXTRA_SERVE_ARGS}\`
- splitmerge_lib: \`${VLLM_SPARSE_MLA_M1_SPLITMERGE_FINAL_LIB}\`
EOF
}
